### ISSUE TITLE
Wird es hier auch ein Update auf 2404 geben? :) 

### ISSUE THREAD

**Issue by RobinArtenjakInit** [coremedia-contributions/blueprint-svg-support#2]

**Comment by sbuettne** [comment]
Hi Robin,
I just updated the plugin for the CMCC 12 2404 release.
Please grab the [cmcc-12-2404.1](https://github.com/coremedia-contributions/blueprint-svg-support/releases/tag/cmcc-12-2404.1) tag.

/Sebastian
